### ISSUE TITLE
macOS linking error

### ISSUE THREAD

**Issue by zhangyubaka** [Dead2/CryptoGoblin#10]
I followed instruction and ran build.sh
This is full output
https://gist.github.com/zhangyubaka/a3b8e8bf5a1710ad2a584bcee805aa7b

Using macOS 10.13.6
Xcode 10 beta3

**Comment by Dead2** [comment]
I have never used macOS myself, but it seems like it might be Clang-related.

CryptoGoblin is specifically optimized for GCC, so using Clang might result in a slower miner.
If you want to try to install actual GCC on your machine, try to follow VikingOSX's howto here:
https://discussions.apple.com/thread/8211796

If you want to try to get Clang working, then you might want to edit build.sh and set hwloc="OFF", verbose="ON" and onlyxmr="ON".
That might help in diagnosing the problems, but I suspect that you need to set lto="OFF" to make it actually work, although that will remove some of the optimizations.

Please report back :)

**Comment by Dead2** [comment]
hwloc and onlyxmr only cuts down on the warnings/errors to make it easier to see the relevant parts. Did you try to disable lto too?

The gcc-8 build looks promising though, but since I don't use mac and thus not xcode, brew or any of the other devel-environments, I can only attempt to nudge you in the right direction.
That said, I am thinking you probably need to install/compile pthreads-libs and pthreads-devel (or similar) using the same devel environment (brew?) as you used to install/compile GCC. Sorry I don't have any more specific advice than that, but I hope that is the hint you need to figure it out yourself. :)

**Comment by zhangyubaka** [comment]
I am using Homebrew, but pthread is already included(both `/usr/include` and `/usr/local/include`)
GCC just doesn't find them, no idea. Clang works fine but can't link the final executable.
https://gist.github.com/zhangyubaka/f65e9a754e56a05b52e7002ca18e70cd

**Comment by Dead2** [comment]
It is weird that cmake does not find pthreads.h when using GCC, it still makes me wonder whether it is a homebrew problem, maybe you need to install cmake via homebrew instead of other source too, in order to get one that is compatible with gcc?

If that does not help, this is an untested hack, but it might be enough in your case.
Add the include_directories line in the below spot in CmakeLists.txt
```
# Find PThreads
################################################################################

include_directories( SYSTEM /usr/include /usr/local/include )
if(NOT WIN32)
```
*crossing fingers*

**Comment by zhangyubaka** [comment]
@Dead2

**Comment by Dead2** [comment]
Huh, my last reply did not appear, strange.

Perhaps install gnu-ld? Might have to tell cmake to use it specifically too, if it does not automatically switch to it.

**Comment by zhangyubaka** [comment]
@Dead2 There is no “GNU LD”…binutils states GNU LD doesn’t support Darwin(macOS) platform …

**Comment by Dead2** [comment]
Ah, then you likely need to set lto="OFF".
That should probably make it work, although with a few missing optimizations. 
It will likely also solve the problem with unsupported linker flags, so put those back and only remove single flags if any give errors still. (Warnings can usually be ignored)

**Comment by zhangyubaka** [comment]
@Dead2 All error occurs with LTO even off...
I always put LTO to off.

**Comment by zhangyubaka** [comment]
@Dead2 I made it with LTO=ON!
Step1: Install gcc from Homebrew
Step2: Modify CMakeList.txt Line 129 remove all extra linker flags
Step3: Compile with CC=GCC-8 CXX=G++-8 NM=gnm RANLIB=granlib AR=gar ./build.sh
This is my successful build log:https://gist.github.com/zhangyubaka/702a63c3d2fd7a4be3aa493834511f42

Hooray!

**Comment by Dead2** [comment]
👍
