### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by TerdyTheTerd** [Dead2/CryptoGoblin#9]
Why am I being told by windows that the file "CryptoGoblin.win10-v2.2.0-XMR-Only.exe" that I cloned from this repo contains a trojan, "TrojanDropper:Win32/Sirefef.gen!C". Guessing it was either packed with this, someone managed to hijack the repo (unlikely) or its a false positive? It could very well be something else in my system causing this file to be falsely pinged, but who knows, doesn't hurt to post about it.

**Comment by Dead2** [comment]
That is a false positive.
Almost all miners are detected as trojans or PUP due to people using them in trojans or hacking machines and installing miners. Nothing we can do about it unfortunately.

Avast on my machine will delete the .exe file right after it has been compiled for example, so whitelisting a folder is unfortunately the way to go.

Some antivirus programs allows you to run a program sandboxed though, that would make it unable to access the rest of the system (documents, other programs, the system files, etc), and that is probably the most secure way to run a miner since they do not need that access anyways.
